# Generated by Django 4.1.6 on 2023-02-19 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='Owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='Title',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
