# Generated by Django 4.1.6 on 2023-02-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_likedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Comments',
            field=models.JSONField(default=list),
        ),
    ]
